services:
  frontend:
    build:
      context: ./contact-app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - './infra/grafana/dashboards:/etc/grafana/provisioning/dashboards'
      - './infra/grafana/datasources:/etc/grafana/provisioning/datasources'
      - './infra/grafana/config:/etc/grafana-config'
      - './infra/grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - grafana-storage:/var/lib/grafana
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observability

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
      - "8027:8027"
    entrypoint:
      - '/bin/alloy'
      - 'run'
      - '--server.http.listen-addr=0.0.0.0:12345'
      - '--config.extra-args="-config.expand-env"'
      - '/etc/alloy/config.alloy'
    volumes:
      - ./infra/alloy/config.alloy:/etc/alloy/config.alloy
    networks:
      - observability

  nginx:
    image: nginx:latest
    ports:
      - "3101:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - alloy
    networks:
      - observability
volumes:
  grafana-storage:

networks:
  observability:
