services:
  # React app service
  frontend:
    build:
      context: ./contact-app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - monitoring

  # NGINX service
  nginx:
    image: nginx:alpine
    ports:
      - "3101:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - monitoring
    depends_on:
      - frontend 

networks:
  monitoring:
    driver: bridge
