services:
  frontend:
    build:
      context: ./contact-app
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    networks:
      - observability

  nginx:
    image: nginx:alpine
    ports:
      - "3101:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - observability
    depends_on:
      - frontend 

networks:
  observability:
    driver: bridge
