server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push  # Loki's endpoint

# tells Promtail where to find logs, 
# which files to read, and 
# what labels to attach before sending logs to Loki.
scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: ["nginx"]
        labels:
          job: nginx
          env: local
          __path__: /var/log/nginx/*.log

  - job_name: frontend
    static_configs:
      - targets: ["frontend"]
        labels:
          job: frontend
          env: local
          __path__: /logs/frontend/*.log

