apiVersion: 1

deleteDatasources:
  - name: 'Loki'

datasources:
  - name: 'Loki'
    type: 'loki'
    access: 'proxy'
    orgId: 1
    url: 'http://loki:3100'
    basicAuth: false
    version: 1
    editable: false
    uid: 'loki'
    jsonData:
      maxLines: 1000